version: '3.7'
services:
  php-app:
    container_name: php-app
    restart: always
    depends_on:
      - database
      - phpmyadmin
      - redis
    image: php-app
    build:
      context: .
      dockerfile: AlpinePHP.Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "composer install && php -S php-app:8000 -t public"
    ports:
      - 8000:8000
    networks:
      - net
  database:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superuser
      MYSQL_DATABASE: development
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - net
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: superuser
    networks:
      - net
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - net

networks:
  net:
    driver: bridge
